### PR TITLE
[WIP] Unified dandi publish/archive docker-compose

### PR DESCRIPTION
**Pull request by mvandenburgh**
Builds both `dandiarchive` and `dandi-publish` with docker-compose. After running the initial `docker-compose up` you need to generate a girder API key, set the `DJANGO_DANDI_GIRDER_API_URL` and `DJANGO_DANDI_GIRDER_API_KEY` env variables in `dev/.env.docker-compose`, and then rerun `docker-compose up`.

Based on #55

### CODE REVIEW

**Comment by yarikoptic** [comment]
<details>
<summary>I guess this PR will help elderly me to get started, since currently this is what I get:</summary> 

```shell
(git)lena:~/proj/dandi/dandi-publish[master]git
$> ./dev/init-minio.sh
Initializing the Minio container and making it ready for Django use:
Creating network "dandi-publish_default" with the default driver
Creating dandi-publish_minio_1 ... done
Waiting for Minio to start ... done
Unable to find image 'minio/mc:latest' locally
latest: Pulling from minio/mc
21c83c524219: Pull complete 
dfb0b6f5fe17: Pull complete 
Digest: sha256:2222e7cca6e1fb877d7dbacfd704d836c595fcc41baa29f99eadc1571933de6c
Status: Downloaded newer image for minio/mc:latest

$> docker-compose run --rm web ./manage.py migrate 
Creating dandi-publish_rabbitmq_1 ... done
Starting dandi-publish_minio_1    ... done
Creating dandi-publish_db_1       ... done
Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    main()
  File "./manage.py", line 23, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/local/lib/python3.8/site-packages/configurations/importer.py", line 182, in load_module
    reraise(err, "Couldn't setup configuration '{0}'".format(cls_path))
  File "/usr/local/lib/python3.8/site-packages/configurations/importer.py", line 164, in load_module
    cls.setup()
  File "/usr/local/lib/python3.8/site-packages/configurations/base.py", line 127, in setup
    setup_value(cls, name, value)
  File "/usr/local/lib/python3.8/site-packages/configurations/values.py", line 15, in setup_value
    actual_value = value.setup(name)
  File "/usr/local/lib/python3.8/site-packages/configurations/values.py", line 105, in setup
    raise ValueError('Value {0!r} is required to be set as the '
ValueError: Couldn't setup configuration 'dandi.settings.DevelopmentConfiguration':  Value 'DANDI_GIRDER_API_KEY' is required to be set as the environment variable 'DJANGO_DANDI_GIRDER_API_KEY' 

```
</details>

**Comment by mvandenburgh** [comment]
@yarikoptic I'm don't think the docker-compose in this PR is functional yet. The error you're getting can be resolved if you follow the steps [here](https://github.com/dandi/dandi-publish/tree/document-env-vars#connecting-to-dandiarchive) (those will soon be merged into `master`).

**Comment by mgrauer** [comment]
It's too much complexity to manage a docker-compose that works for both services (dandi-publish, dandiarchive) integrated. At least for now, the current docker-composes do not interfere with each other, and that is sufficient.

**Comment by yarikoptic** [comment]
Note: whenever "publish" (AKA API) is deployed we will desire a unified docker-compose for a number of reasons including testing.

**Comment by jwodder** [comment]
What is the origin of `minio.Dockerfile`?  It is currently failing to build:

```
Step 8/11 : RUN   sh -c "/usr/bin/docker-entrypoint.sh minio server ${MINIO_BACKEND_DIR} &" &&   until nc -z localhost 9000; do sleep 1; done &&   ./mc config host add minio http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&   ./mc admin user add minio ${MINIO_USER_ACCESS_KEY} ${MINIO_USER_SECRET_KEY} &&   ./mc admin policy set minio readwrite user=${MINIO_USER_ACCESS_KEY}
 ---> Running in 9b97c437be9d
Attempting encryption of all config, IAM users and policies on MinIO backend
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
ERROR: Service 'minio' failed to build: The command '/bin/sh -c sh -c "/usr/bin/docker-entrypoint.sh minio server ${MINIO_BACKEND_DIR} &" &&   until nc -z localhost 9000; do sleep 1; done &&   ./mc config host add minio http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&   ./mc admin user add minio ${MINIO_USER_ACCESS_KEY} ${MINIO_USER_SECRET_KEY} &&   ./mc admin policy set minio readwrite user=${MINIO_USER_ACCESS_KEY}' returned a non-zero code: 1
```

**Comment by yarikoptic** [comment]
This PR was never merged.

@jwodder can't we just use `girder/minio-nonroot` image as provisioned in https://github.com/dandi/dandi-publish/blob/master/docker-compose.yml ?  or we really need to finalize this PR for the ultimate single compose setup?

**Comment by jwodder** [comment]
If I copy the minio configuration from master and update the django & celery environment variables to match those on master, `docker-compose run --rm django ./manage.py migrate` fails with:

```
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/django/dandi/publish/models/__init__.py", line 1, in <module>
    from .asset import Asset
  File "/opt/django/dandi/publish/models/asset.py", line 34, in <module>
    class Asset(TimeStampedModel):
  File "/opt/django/dandi/publish/models/asset.py", line 48, in Asset
    blob = DeconstructableFileField(
  File "/opt/django/dandi/publish/storage.py", line 36, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/django/dandi/publish/storage.py", line 18, in __init__
    self.storage = self.storage()
  File "/opt/django/dandi/publish/models/asset.py", line 27, in _get_asset_blob_storage
    return create_s3_storage(settings.DANDI_DANDISETS_BUCKET_NAME)
  File "/opt/django/dandi/publish/storage.py", line 119, in create_s3_storage
    storage = VerbatimNameMinioStorage(
  File "/opt/django/dandi/publish/storage.py", line 57, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/minio_storage/storage.py", line 75, in __init__
    self._init_check()
  File "/usr/local/lib/python3.8/site-packages/minio_storage/storage.py", line 89, in _init_check
    if self.auto_create_bucket and not self.client.bucket_exists(
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 404, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2185, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2063, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2105, in _get_bucket_location
    raise ResponseError(response, method, bucket_name).get_exception()
minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.
```

If I try just running `docker-compose run --rm django ./manage.py migrate` on the master branch of dandi-publish, it fails with:

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0009_remove_description, 0010_timestampedmodel in publish).
To fix them run 'python manage.py makemigrations --merge'
```

**Pull request closed without merging**
